### PR TITLE
adds option to automatically revert backticks (again) and fixes some bugs related to it

### PR DESCRIPTION
**Pull request by xNocken**
related issues: #47 #43

### CODE REVIEW

**Comment by karlhorky** [comment]
In case this gets merged, then https://github.com/meganrogge/template-string-converter/issues/44 can be reopened too

**Comment by karlhorky** [comment]
In reviewing whether this should be merged or not, some things to check are:

- the multiple issues reported in https://github.com/meganrogge/template-string-converter/issues/43
- the critical issue in https://github.com/meganrogge/template-string-converter/issues/47

**Comment by meganrogge** [comment]
Thanks for resolving the issues @xNocken and for the bug reporting @karlhorky.

**Review by meganrogge — APPROVED** [review]

**Comment by karlhorky** [comment]
So this has been released in `0.4.9` right?

Just taking a look at [the extension page](https://marketplace.visualstudio.com/items?itemName=meganrogge.template-string-converter), it seems like this option is not documented.

@xNocken could you add this to [the `README.md`](https://github.com/meganrogge/template-string-converter/blob/master/README.md), maybe with a gif illustrating the feature?

**Comment by meganrogge** [comment]
Done @karlhorky

**Comment by karlhorky** [comment]
Thanks!! I'll have to re-enable this and give it a try extensively.

**Comment by karlhorky** [comment]
Ok, so it seems this feature is still somewhat buggy: 

It erroneously makes the following into a double-quoted string, when hitting backspace inside of it.

Notice there are no interpolations. It's important that it stay as a tagged template string.

```ts
export async function down(sql: Sql<{}>) {
  await sql`DROP TABLE reset_password_requests`;
}
```

**Comment by karlhorky** [comment]
I'm guessing the logic for this feature is:

1. If the user is inside a template string AND hits backspace:
    1. switch to double quotes

This is maybe almost ok, but should probably do some better checks:

1. If the user is inside a template string AND there is an interpolation (`${` and `}` present in the string) AND there is NO interpolation AFTER hitting backspace:
    1. switch to double quotes

That seems like it would be a much more robust start of an implementation (probably also has weird edge cases, but at least it's much better than what's there now).

**Pull request merged**
